### ISSUE TITLE
Please document the compile process for github pages

### ISSUE THREAD

**Issue by ghost** [knode/knode.github.io#23]
I would like to contribute but I'm unsure about how the current github pages are being compiled. If I recall right GHP only works with static html and jekyll currently. So how is it possible that if the output folder is compiled via js but is being ignored in git that it works with GHP?

**Comment by hackygolucky** [comment]
@chrisdickinson Care to take a stab at it?

**Comment by chrisdickinson** [comment]
Right now it's being done manually -- i.e., when there are changes to any of the constituent content repos (meetups, speakers, cfp, blog, docs) or templates, this repo needs to have a contributor re-run the install / compile steps, move the results out into the main dir, and commit, then push to master. Styles, however, run in their own repo -- so you can pr into gh-pages on knode/style and change CSS for the main site without having to touch this repo at all.

The intention is to move in the following direction:
1. Move the knode.github.io build scripts off of "master" (to branch "development").
2. Switch the "primary" branch of knode.github.io to the "development" branch. GH-pages is, ideally, built off of master, while the build tools live in "development".
3. Add a npm scripts command to the build to automatically commit the changes contained in `output/` to the "master" branch.
4. Wire that up to travis-ci, have auto-rebuilds on changes.

An additional, fuzzier architectural thought:
1. If we move templates out of this repo, we could additionally give control of the subpaths to their constituent content repos. That is to say, we can get away from knode.github.io importing "meetups" to build `knode.io/meetups`, and instead that repo will have its own `gh-pages` branch.
2. This still requires rebuilds of `knode.github.io` for things to be featured on the front page of the site, but each repo being responsible for its own path might make things a bit easier to maintain in the future.
