### ISSUE TITLE
KnodeCamp Contact Info

### ISSUE THREAD

**Issue by rosskukulinski** [knode/knode.github.io#24]
I wanted to consolidate Github/Twitter contact info for everyone who attended KnodeCamp.  Feel free to post your details so we can keep in touch.

Ross Kukulinski
Twitter: [@rosskukulinski](https://twitter.com/rosskukulinski)
Github: [rosskukulinski](https://github.com/rosskukulinski/)

**Comment by shamod** [comment]
Shamod Lacoul
Twitter: @shamod
Github: shamod

**Comment by mschmulen** [comment]
Matt Schmulen
Twitter: @mattschmulen
Github : mschmulen

**Comment by chrisgervang** [comment]
Chris Gervang
Twitter: @chrisgervang
Github: chrisgervang

**Comment by mikeal** [comment]
Mikeal Rogers
@mikeal on everything.

**Comment by terinjokes** [comment]
Terin Stock
@terinjokes on lots of things

**Comment by lakenen** [comment]
Cameron Lakenen
@lakenen on everything

**Comment by boolpath** [comment]
Jorge Zaccaro
@jorgezaccaro on everything

**Comment by hackygolucky** [comment]
@hackygolucky on errrthing up in herr

**Comment by rosskukulinski** [comment]
Moved everyone's info to https://github.com/knode/knode.github.io/wiki
