### ISSUE TITLE
knode.io 404ing

### ISSUE THREAD

**Issue by ungoldman** [knode/knode.github.io#26]
Is knode still going?

**Comment by rosskukulinski** [comment]
hi @ngoldman -- We should probably take down this repository -- Most of the content has shifted to [node-forward](http://nodeforward.org/)

**Comment by ungoldman** [comment]
@rosskukulinski that site appears to be unresponsive -- not 404ing, just timing out.

http://www.downforeveryoneorjustme.com/nodeforward.org

:frowning:

**Comment by rosskukulinski** [comment]
Oh no!  It was working when I posted the link

**Comment by hackygolucky** [comment]
it was an expensive domain :-/ I did try to renew it but it was too
late(.io TLD requires a different re-up than a .com for expiry). I'll
update this repo to reflect the project status. Sorry folks.

**Comment by mikeal** [comment]
Let's have a Post Mortem to learn from this https://github.com/knode/node-meatspace/issues/125
