### ISSUE TITLE
Meetups page layout thoughts

### ISSUE THREAD

**Issue by hackygolucky** [knode/knode.github.io#6]
Thinking of having a featured meetup, timed for rotating out every 24 hours. On the events page:

+-------------------------------------------------------------------------------------------+
 |                                                                                                                   |
 |                                                                                                                   |  
 |                                          FEATURED                                                   |
 |                                             MEETUP                                                     |
 |                                                                                                                   |
 |                                                                                                                   |
+-------------------------------------------------------------------------------------------+
+------------------------+ +------------------------------+ +-----------------------------+
 |                               |  |                                       |  |                                      |
 |                               |  |                                       |  |                                      |
 |      awesome        |  |        another super      |  |             !yay!                 |
 |         meetup         |  |            meetup             |  |             event                |
 |                               |  |                                       |  |                                      |
+------------------------+ +-----------------------------+  +------------------------------+
....way more of these ascii boxes that I'm horrible at making...

**Comment by hackygolucky** [comment]
Oh gah, I'm horrible at ascii. This did not work at all. Apologies. The idea is just to have a larger rectangle featured box and the smaller squares for all meetups. Click-through will result in the listing of meetups with the one you've clicked on at the top( I guess a sort feature, I might hate myself later for this) with details about the meetup displayed. This would require the contributor submitting the info to supply a banner and a square/avatar image. We can fill them in otherwise.

**Comment by chrisdickinson** [comment]
What audience/problem would the hero/3-subordinate layout address? It might be a useful exercise to enumerate the goals / audiences we're trying to reach with the site.

> This would require the contributor submitting the info to supply a banner and a square/avatar image.

I've waffled on this a lot. Avoiding graphical contributions is nice in that it lowers the barrier for entry in terms of listing your meetup. This is totally anecdotal, but I have a tendency to avoid submitting these sorts of things unless I can fill in every field (due to wanting to have things "perfect" instead of "good"). 

On the other hand, it'd be nice to be able to graphically represent meetups -- and further, to connect organizers with folks who can make logos for them. I'm currently leaning towards not putting it into the template and grabbing that info ourselves as new meetups get merged -- and if a given meetup doesn't have a logo we can see about helping them procure one, if they so desire.

**Comment by hackygolucky** [comment]
I wrestled with the same thought. Happy to put in the extra work myself to
fetch relevant images.

**Comment by chrisdickinson** [comment]
@hackygolucky Yeah. I agree -- I think I'd like to keep the image-gathering to a manual process on our end (pinging back folks who contribute to see if they have a logo they'd like to use).

Going out on a limb here: the end goal of this layout is to enhance our ability to highlight different meetups -- and by extension, provide value to meetups being featured. However, I imagine twitter would be a better vehicle for highlighting meetups and their upcoming events -- there's already a good following model, embedded media, etc.

To enhance our ability to assist meetups and organizers past tweeting about events and meetups, Knode's site might be better served by showcasing articles _about_ individual meetups, event postmortems, interviews with organizers / community members, etc. Then we could address the "find a community near me" problem separately with a map or list view of available meetups.

**Comment by hackygolucky** [comment]
So then is the idea that we wouldn't want to display the meetups or that
I'm overcomplicating what should be featured on the site?

**Comment by hackygolucky** [comment]
https://www.dropbox.com/s/p2epa5vvipt3itr/knode_layout.jpg
https://www.dropbox.com/s/fxc33l7y63mk28m/knode_discussion.jpg
https://www.dropbox.com/s/9dw163vu7spyesm/knode_more_ia.jpg
https://www.dropbox.com/s/w687p5kw2n8ofme/knode_ia_sketch.jpg
